### ISSUE TITLE
Not possible to set keymap

### ISSUE THREAD

**Issue by carshadi** [JaneliaSciComp/hortacloud#5]
Tools > Options > Keymap

Set the hotkey for the "Add/Edit Note" action to "N". 
Press "Apply" and "OK".

Select a point in Horta 3D and press "N" - nothing happens. The expected behavior would be to see the "Add note" dialog pop up.

This also is the case for the other hotkeys.

**Comment by olbris** [comment]
This could be a combination of two things:

- first, Horta sometimes but not always requires a restart before keyboard shortcuts take effect; when I tested this morning, HortaCloud (Janelia instance) needed a restart
- second, in order for shortcuts to persist across sessions, the instance needs user persistence to be turned on; as of today, it is not turned on in the Janelia instance

The last test you can do is to change a keyboard shortcut then restart Horta without quitting your session. It should work in that case (and does in the Janelia instance). If it does not, then that's a new bug we haven't seen.

**Comment by carshadi** [comment]
I tried changing a shortcut then restarting, but trying to open a workspace yields this error. This seems to happen most (every?) times I restart the workstation within a session.

```
java.net.UnknownHostException: workstation.int.janelia.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:613)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1051)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1049)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1048)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1577)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:97)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1497)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1495)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1494)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:378)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:267)
Caused: javax.ws.rs.ProcessingException
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:269)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313)
	at org.janelia.workstation.controller.access.TiledMicroscopeRestClient.getWorkspaceNeuronCount(TiledMicroscopeRestClient.java:217)
	at org.janelia.workstation.controller.access.TiledMicroscopeDomainMgr.streamWorkspaceNeurons(TiledMicroscopeDomainMgr.java:244)
	at org.janelia.workstation.controller.model.annotations.neuron.NeuronModelAdapter.loadNeurons(NeuronModelAdapter.java:52)
	at org.janelia.workstation.controller.model.annotations.neuron.NeuronModel.loadWorkspaceNeurons(NeuronModel.java:209)
	at org.janelia.workstation.controller.access.ProjectInitFacadeImpl$2.doStuff(ProjectInitFacadeImpl.java:178)
	at org.janelia.workstation.core.workers.SimpleWorker.createResult(SimpleWorker.java:14)
	at org.janelia.workstation.core.workers.SimpleWorker.createResult(SimpleWorker.java:10)
	at org.janelia.workstation.core.workers.ResultWorker.doInBackground(ResultWorker.java:50)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[catch] at java.lang.Thread.run(Thread.java:750)

```

**Comment by cgoina** [comment]
What version of the workstation do you have? I experienced this in 9.10. I think this should be fixed starting with 9.10.2. I just deployed the latest. Then I killed the workstation and redeployed it and it seems it's doing the right thing. Please wait until @dyf deploys the latest and then see if you can replicate it.

**Comment by carshadi** [comment]
After the deployment I am able to restart the workstation and the keyboard shortcuts now work!

**Comment by cgoina** [comment]
@carshadi can we close this ticket then?
